CargoServices/Controllers/RolesController.cs
using CargoServices.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CargoServices.Controllers
{
    public class RolesController : Controller
    {
        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Roles
        public ActionResult RoleList()
        {
            var roleList = db.Roles.ToList();
            return View(roleList);
        }

        public ActionResult CreateRole()
        {
            var role = new IdentityRole();
            return View(role);
        }
        [HttpPost]
        public ActionResult CreateRole(IdentityRole identity)
        {
            db.Roles.Add(identity);
            db.SaveChanges();
            return RedirectToAction("RoleList");
        }
    }
}

CargoServices/Views/Roles/CreateRole.cshtml
@model  Microsoft.AspNet.Identity.EntityFramework.IdentityRole
@{
    ViewBag.Title = "CreateRole";
}

<h2>CreateRole</h2>

@using (Html.BeginForm("CreateRole", "Roles"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CreateRole</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "RoleList")
</div>

CargoServices/Views/Roles/RoleList.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "RoleList";
}

<h2>RoleList</h2>
<p>
    @Html.ActionLink("Create Role", "CreateRole", "Roles")
</p>
<table>
    <thead>
        <tr>
            <th>
                Role Name
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.Name
                </td>
            </tr>
        }
    </tbody>
</table>